### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by shivergard** [shadown/Commenter#1]
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./Commenter.py", line 204, in run
  File "./Commenter.py", line 41, in getDatabaseForRootFolder
  File ".\genericpath.py", line 41, in isdir
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by shadown** [comment]
What version of Sublime Text are you using and under what platform?

**Comment by shivergard** [comment]
2.0.1 , Build 2221

**Comment by shivergard** [comment]
Environment : Ubuntu 14.04 32bit

**Comment by shadown** [comment]
did you follow the configuration as described in the documentation?
Where it says:
Open Commenter.sublime-settings and customize the setting as you want.
...
Be sure to set "bookmarks_folder" to the directory you want to store the bookmark-database files.

**Comment by shivergard** [comment]
Yes ... i did that... reloaded sublime... but doesn't show activity 

{
    "debug"             : false,
    "show_context_menus": true,
    "bookmarks_folder"  : "/opt/worknet/comments/",
    "bookmarks_prefix"  : "comm_",
    "bookmarks_postfix" : "_comments",
    "bookmarks_ext"     : "db"
}

**Comment by shadown** [comment]
1) It doesn't show any activity or is it still throwing that error you post before?

2) The configuration options are as described in the installation instructions:
{
    "debug"             : false,
    "bookmarks_folder"  : "/Users/shadown/.subl_commenter",
    "bookmarks_prefix"  : "",
    "bookmarks_postfix" : "_comments",
    "bookmarks_ext"     : "db"
}

There's _no_ "show_context_menus" option.

btw, you should eliminate the last '/' from your bookmarks_folder path.

**Comment by shadown** [comment]
closing as per silence of a user who has not read the instructions. lame.

**Comment by shivergard** [comment]
... I've read . But it did not help. Did what you suggested. 

No activity is that plugin is not working : then on console it shows errors... But ... u can close it , cause I'm not using this anyway. To much time spent on it anyway ;)

**Comment by shivergard** [comment]
And I read instructions . Just ... it is more look like code issue to , if in instruction you have one param less , than in sample configuration ...

**Comment by shadown** [comment]
I've tested it on Windows, Linux and OSX, on both Sublime Text 2 and 3, so did my friends and a bunch of other people. Non had any issue.

If you were looking for a context menu, point and click solution, then this ones is not for you.

The only thing that comes to my mind is if you had some key bindings that overlap with the default ones I've chosen, which is as simple as reassigning them in your user keybinding settings.

**Comment by shadown** [comment]
I ask for apologies for the context menu parameter, you are right on that one. Sorry about that. I'll delete that from the repo to avoid confusions.

**Comment by shivergard** [comment]
Checked key binding collision too. Maybe latter will check out some more : If I'll understand , why and what caused I'll attach ... now I have a lack of time.

Anyhow , thank you for help ;)
